### ISSUE TITLE
Symmetric encryption signature keys are handled as null-terminated C-strings

### ISSUE THREAD

**Issue by JesseEstum** [AnthonyDeroche/mod_authnz_jwt#13]
Signature keys (e.g., the ones specified in httpd.conf with AuthJWTSignatureSharedSecret) are assumed to be null-terminated C-strings.  This is a problem if the signature key contains a null byte as part of it, which is entirely legal and not uncommon for encryption keys.

This could be fixed by using functions like strncpy instead of strcpy and passing around the length of the keys.

**Comment by AnthonyDeroche** [comment]
I added the possibility to use null-byte characters in keys.
Could you tell me if it's ok for you. I will create a new release just after.
Thanks

**Comment by JesseEstum** [comment]
@AnthonyDeroche I tested this out but unfortunately I think it has a bug.

It can be reproduced with the following configuration:
```
AuthJWTSignatureAlgorithm HS512
AuthJWTSignatureSharedSecret FtEA6C6kqp5O2X8mitg3Dd4FM4tBP2Tb8Fck06TNTa4Bq1jx441v8ovC9IUi2Zez+YoYtT9Ln7vMqTAjDdGB+g==
```
Response from server:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

I believe the issue here is that the actual key length (in bytes) is not accurately reflected in the return value from `apr_base64_decode_len`.  The [documentation](https://apr.apache.org/docs/apr/2.0/group___a_p_r___util___base64.html#gad1ba714a6708376e6a21722a40a698a2) for this function states that it returns the maximum buffer size needed to do the decoding, but doesn't explicitly state that it returns the length of the decoded value.  For the 64 byte signature key I used, `apr_base64_decode_len` returned 67.  Older versions of APR seem to have behaved differently according to the docs.

What about changing the implementation to obtain the key length based on the specified encryption algorithm?  E.g., HS512 implies 64 bytes.  The only risk to this approach (that I can think of, anyway) is copying more bytes than are allocated to the buffer.  This could easily be guarded against by validating that key length <= return value from `apr_base64_decode_len`.

**Comment by AnthonyDeroche** [comment]
Ok thanks for your feedback. I will look at this asap. I did not see the documentation states this is the maximum size of the buffer.

**Comment by jeroenvv** [comment]
I also encountered an issue with this for long key strings and HS256, for example a random generated key d0NuMmY4dDVlZkNLNkVzd2lTOGU4ZkFoRlJCdTg0RGZUWVJTemZyWUxycFlKanplZGhqQ1ZGUTZ4NGhKSDJTRw==
Short keys worked, but security suggests using at least 64-byte keys.
