### ISSUE TITLE
Cannot load mod_authnz_jwt.so... libjwt.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by vanyabrovary** [AnthonyDeroche/mod_authnz_jwt#22]
Debian jessie, Apache/2.4.10.

**Error after installation:**

apache2: Cannot load /usr/lib/apache2/modules/mod_authnz_jwt.so into server: libjwt.so.0: cannot open shared object file: No such file or directory

**ldd:**

`ldd /usr/lib/apache2/modules/mod_authnz_jwt.so`
`libjwt.so.0 => not found`

**Fix:**

`cp /usr/local/lib/libjwt.*  /lib/x86_64-linux-gnu/`

**ldd:**

`ldd /usr/lib/apache2/modules/mod_authnz_jwt.so`
`libjwt.so.0 => /usr/local/lib/libjwt.so.0`

**Comment by Krever** [comment]
Have the same error in official `httpd:2.4` docker image.
Fixed by `ENV LD_LIBRARY_PATH /usr/local/lib`
