### ISSUE TITLE
[Feature] cookie

### ISSUE THREAD

**Issue by ghetolay** [AnthonyDeroche/mod_authnz_jwt#28]
Would it be viable to add an option for the cookie variant ? 

We would need to set a cookie (name configurable) at login and during access check for it instead of the Authorization header.

**Comment by ghetolay** [comment]
I need cookie to protect static assets (js, css, svg, images...) that you don't load using js and so can't alter the headers sent on the request. Also there is now `SameSite` attribute to protect againt CSRF.

I've started [working on it](https://github.com/ghetolay/mod_authnz_jwt/tree/cookie), I'll open a PR once I'm done.

**Comment by AnthonyDeroche** [comment]
Ok perfect. Thanks for contributing.
