### ISSUE TITLE
[Feature] Add extra claim field

### ISSUE THREAD

**Issue by LSChyi** [AnthonyDeroche/mod_authnz_jwt#33]
Would it be possible to add extra claim field and value when issuing JWT token in configuration?

Like giving each user a role to specify its privilege.

**Comment by AnthonyDeroche** [comment]
There is such a feature for now. The simplest way to achieve that is to emit tokens from your app and use the module only for verifying purpose.
You can also submit a PR if you are interested in having this in the module!
