### ISSUE TITLE
Invalid command 'AuthJWTDeliveryType'

### ISSUE THREAD

**Issue by mpollitt** [AnthonyDeroche/mod_authnz_jwt#47]
Hi guys, 

I am some having some issue with setting this part of my apache config?  I am I missing something from apache set up.  

"Invalid command 'AuthJWTDeliveryType', perhaps misspelled or defined by a module not included in the server configuration"

**Comment by AnthonyDeroche** [comment]
Are you sure that the module is loaded ? If so, it is the last version (1.2.0) ?
