### ISSUE TITLE
AH55204: auth_jwt authn: the expected parameter user is missing, aborting authentication

### ISSUE THREAD

**Issue by moshesilva** [AnthonyDeroche/mod_authnz_jwt#58]
HI,
    I am using this module for test JWT with apache HTTPD, but I am getting this error during the test on http log

![error_httpd_logs](https://user-images.githubusercontent.com/22133295/118894986-ab868300-b8db-11eb-9e01-d85d6cd9539b.png)

   **Apache conf for test**

![apache_conf_jwt](https://user-images.githubusercontent.com/22133295/118895035-c5c06100-b8db-11eb-99c3-4764ff038f78.png)

   **ScreenShot of the browser**

   
![postman_browser](https://user-images.githubusercontent.com/22133295/118895082-dc66b800-b8db-11eb-8c55-c3ab60c1732c.png)

     Could you help me with this problem?
     
Thanks,

**Comment by AnthonyDeroche** [comment]
Hello

The token must contain a field "user" with a value. Is it the case ?
